language: node_js
node_js: "12"
branches:
  only:
    - working
    - main
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
